### ISSUE TITLE
Automate update

### ISSUE THREAD

**Issue by dmolineus** [phpcq/repository#1]
Wer might use GitHub actions for automation. At least a Cron job based update should work, see https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

**Comment by discordier** [comment]
Good idea, I'll have to check how to automate the push then however.

**Comment by dmolineus** [comment]
- https://github.com/marketplace/actions/github-push
- https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by discordier** [comment]
I have appended to your branch, however we can not commit there, as the name and email of the "author" is not given - I wonder what we should put there.

**Comment by dmolineus** [comment]
Close in favour of #3
